--liquibase formatted.sql
--changeset michael.cawayan:SDM.TRG_LCM_PROD_ELIG contextFilter:PH endDelimiter:/ runOnChange:true

--1st trigger, run below once DCT_CLIENT_LIFECYCLE_MTRX is updated/inserted
CREATE or replace TRIGGER SDM.TRG_LCM_PROD_ELIG
    AFTER UPDATE OR INSERT
    ON SDM.DCT_CLIENT_LIFECYCLE_MTRX
    FOR EACH ROW
BEGIN

INSERT INTO CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY(PARTY_ID, REAL_CLX_FLAG, REAL_CC_FLAG, REAL_POS_FLAG, ENGAGEMENT_FLAG, HOOK_CLX_FLAG, HOOK_CC_FLAG, HOOK_POS_FLAG, DATE_CREATED)
WITH CUSTOMER_TB AS (
SELECT PARTY_ID
FROM INT_OS.V_OFFER 
WHERE PARTY_ID IN (
SELECT ID_CUID FROM SDM.DCT_CLIENT_LIFECYCLE_MTRX
WHERE 1=1
--AND LAST_UPDATE_DT = SYSDATE
)
)
, OFFERS AS (
SELECT 
C.PARTY_ID,
O.OFFER_TYPE_CODE,
CRM_PILOT_CODE,
OFFER_STATUS,
OFFER_VALID_TO
FROM CUSTOMER_TB C
LEFT JOIN INT_OS.V_OFFER O 
ON C.PARTY_ID = O.PARTY_ID
) 
, OFFERS1 AS (    
SELECT 
O.*,
CASE WHEN O.OFFER_TYPE_CODE LIKE '%HOOK%' THEN 'HOOK'
     WHEN O.OFFER_TYPE_CODE LIKE '%REAL%' THEN 'REAL'
     ELSE NULL END OFFER_TYPE,
CASE WHEN O.CRM_PILOT_CODE LIKE '%POS%' THEN 'POS'
     WHEN O.CRM_PILOT_CODE LIKE '%CLX%' THEN 'CLX'
     WHEN O.CRM_PILOT_CODE LIKE '%CC%' THEN 'CC'
     ELSE NULL END PRODUCT_TYPE      
FROM OFFERS O
)
, CLIENT_PRODUCT_ELIGIBILITY AS (
SELECT 
O.PARTY_ID,
MAX(CASE WHEN O.OFFER_TYPE = 'REAL' AND O.PRODUCT_TYPE = 'CLX' THEN 1 END) AS REAL_CLX_FLAG,
MAX(CASE WHEN O.OFFER_TYPE = 'REAL' AND O.PRODUCT_TYPE = 'CC' THEN 1 END) AS REAL_CC_FLAG,
MAX(CASE WHEN O.OFFER_TYPE = 'REAL' AND O.PRODUCT_TYPE = 'POS' THEN 1 END) AS REAL_POS_FLAG,
MAX(CASE WHEN CC.ID_CUID IS NOT NULL THEN 1 END) AS ENGAGEMENT_FLAG,
MAX(CASE WHEN O.OFFER_TYPE = 'HOOK' AND O.PRODUCT_TYPE = 'CLX' THEN 1 END) AS HOOK_CLX_FLAG,
MAX(CASE WHEN O.OFFER_TYPE = 'HOOK' AND O.PRODUCT_TYPE = 'CC' THEN 1 END) AS HOOK_CC_FLAG,
MAX(CASE WHEN O.OFFER_TYPE = 'HOOK' AND O.PRODUCT_TYPE = 'POS' THEN 1 END) AS HOOK_POS_FLAG,
MAX(SYSDATE) AS DATE_CREATED
FROM OFFERS1 O
LEFT JOIN (
SELECT C.ID_CUID 
FROM SDM.FT_CONTRACT_AD C
LEFT JOIN SDM.FT_APPLICATION_AD A ON C.SKP_CREDIT_CASE = A.SKP_CREDIT_CASE
WHERE C.NAME_CREDIT_STATUS = 'Active'
AND C.SKP_CREDIT_TYPE = 3
AND A.CODE_PRODUCT LIKE '%CC%'
AND A.DTIME_ACTIVATION >= ADD_MONTHS(SYSDATE, -1)
) CC ON O.party_id = CC.ID_CUID
LEFT JOIN SDM.DCT_CLIENT_LIFECYCLE_MTRX M ON M.ID_CUID = O.PARTY_ID
GROUP BY O.PARTY_ID
)
SELECT *
FROM CLIENT_PRODUCT_ELIGIBILITY
WHERE HOOK_POS_FLAG IS NULL;

END;
/