--liquibase formatted.sql
--changeset michael.cawayan:LCM_USER.LIFECYCLE_THRESHOLD_DICT contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE
    v_count NUMBER;
    e_object_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_object_not_exist, -942); -- ORA-00942 (Table or View does not exist)
BEGIN
    -- Check if the table exists
    SELECT COUNT(*) INTO v_count 
    FROM all_tables 
    WHERE table_name = 'LIFECYCLE_THRESHOLD_DICT';
    -- If the table does not exist, raise an exception
    IF v_count = 0 THEN
        RAISE e_object_not_exist;
    END IF;
    -- If exists, proceed with operation
    execute immediate q'{
        DROP TABLE LCM_USER.LIFECYCLE_THRESHOLD_DICT
        }';
        
EXCEPTION
    WHEN e_object_not_exist THEN
        DBMS_OUTPUT.PUT_LINE('Error: Table does not exist.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Unexpected error: ' || SQLERRM);
END;
/
DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE "LCM_USER"."LIFECYCLE_THRESHOLD_DICT" (
    "CALC_PRIORITY_ID" NUMBER(*,0), 
    "POS_ELIGIBILITY_BASE_REAL" NUMBER(*,0), 
    "POS_ELIGIBILITY_BASE_HOOK" NUMBER(*,0), 
    "POS_ELIGIBILITY_BASE_ENGAGEMENT" NUMBER(*,0), 
    "POS_ELIGIBILITY_BASE_WARMUP" NUMBER(*,0), 
    "POS_OFFER_RESIST_OFFER_CNT" NUMBER(*,0), 
    "POS_SCORE_DROP_OFFER_CYCLE" NUMBER(*,0), 
    "POS_OR_MODIFIER_TRIGGER" NUMBER(*,0), 
    "POS_OR_MODIFIER" NUMBER(*,0), 
    "POS_CLIENT_STATUS_1_CHECK" VARCHAR2(10 CHAR), 
    "POS_CLIENT_STATUS_1_MODIFIER" NUMBER(*,0), 
    "POS_CLIENT_STATUS_2_CHECK" VARCHAR2(10 CHAR), 
    "POS_CLIENT_STATUS_2_MODIFIER" NUMBER(*,0), 
    "POS_CLIENT_STATUS_3_CHECK" VARCHAR2(10 CHAR), 
    "POS_CLIENT_STATUS_3_MODIFIER" NUMBER(*,0), 
    "POS_INTEREST_BONUS" NUMBER(*,0), 
    "POS_DISINTEREST_MINUS" NUMBER(*,0), 
    "POS_CLIENT_LIFE_STAGE_CHECK_1" VARCHAR2(10 CHAR), 
    "POS_CLIENT_LIFE_STAGE_BONUS_1" NUMBER(*,0), 
    "POS_CLIENT_LIFE_STAGE_CHECK_2" VARCHAR2(10 CHAR), 
    "POS_CLIENT_LIFE_STAGE_BONUS_2" NUMBER(*,0), 
    "POS_CLIENT_LIFE_STAGE_CHECK_3" VARCHAR2(10 CHAR), 
    "POS_CLIENT_LIFE_STAGE_BONUS_3" NUMBER(*,0), 
    "POS_START_INTENSITY" NUMBER(*,0), 
    "POS_REAL_OFFER_INTENSITY" NUMBER(*,0), 
    "POS_INTENSITY_FALLOFF" NUMBER(*,0), 
    "POS_END_COMMS_OR_TRIGGER" NUMBER(*,0), 
    "CLX_ELIGIBILITY_BASE_REAL" NUMBER(*,0), 
    "CLX_ELIGIBILITY_BASE_HOOK" NUMBER(*,0), 
    "CLX_ELIGIBILITY_BASE_ENGAGEMENT" NUMBER(*,0), 
    "CLX_ELIGIBILITY_BASE_WARMUP" NUMBER(*,0), 
    "CLX_OFFER_RESIST_OFFER_CNT" NUMBER(*,0), 
    "CLX_SCORE_DROP_OFFER_CYCLE" NUMBER(*,0), 
    "CLX_OR_MODIFIER_TRIGGER" NUMBER(*,0), 
    "CLX_OR_MODIFIER" NUMBER(*,0), 
    "CLX_CLIENT_STATUS_1_CHECK" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_STATUS_1_MODIFIER" NUMBER(*,0), 
    "CLX_CLIENT_STATUS_2_CHECK" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_STATUS_2_MODIFIER" NUMBER(*,0), 
    "CLX_CLIENT_STATUS_3_CHECK" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_STATUS_3_MODIFIER" NUMBER(*,0), 
    "CLX_INTEREST_BONUS" NUMBER(*,0), 
    "CLX_DISINTEREST_MINUS" NUMBER(*,0), 
    "CLX_CLIENT_LIFE_STAGE_CHECK_1" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_LIFE_STAGE_BONUS_1" NUMBER(*,0), 
    "CLX_CLIENT_LIFE_STAGE_CHECK_2" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_LIFE_STAGE_BONUS_2" NUMBER(*,0), 
    "CLX_CLIENT_LIFE_STAGE_CHECK_3" VARCHAR2(10 CHAR), 
    "CLX_CLIENT_LIFE_STAGE_BONUS_3" NUMBER(*,0), 
    "CLX_START_INTENSITY" NUMBER(*,0), 
    "CLX_REAL_OFFER_INTENSITY" NUMBER(*,0), 
    "CLX_INTENSITY_FALLOFF" NUMBER(*,0), 
    "CLX_END_COMMS_OR_TRIGGER" NUMBER(*,0), 
    "CC_ELIGIBILITY_BASE_REAL" NUMBER(*,0), 
    "CC_ELIGIBILITY_BASE_HOOK" NUMBER(*,0), 
    "CC_ELIGIBILITY_BASE_ENGAGEMENT" NUMBER(*,0), 
    "CC_ELIGIBILITY_BASE_WARMUP" NUMBER(*,0), 
    "CC_OFFER_RESISTANCE_OFFER_COUNT" NUMBER(*,0), 
    "CC_SCORE_DROP_OFFER_CYCLE" NUMBER(*,0), 
    "CC_OR_MODIFIER_TRIGGER" NUMBER(*,0), 
    "CC_OR_MODIFIER" NUMBER(*,0), 
    "CC_CLIENT_STATUS_1_CHECK" VARCHAR2(10 CHAR), 
    "CC_CLIENT_STATUS_1_MODIFIER" NUMBER(*,0), 
    "CC_CLIENT_STATUS_2_CHECK" VARCHAR2(10 CHAR), 
    "CC_CLIENT_STATUS_2_MODIFIER" NUMBER(*,0), 
    "CC_CLIENT_STATUS_3_CHECK" VARCHAR2(10 CHAR), 
    "CC_CLIENT_STATUS_3_MODIFIER" NUMBER(*,0), 
    "CC_INTEREST_BONUS" NUMBER(*,0), 
    "CC_DISINTEREST_MINUS" NUMBER(*,0), 
    "CC_CLIENT_LIFE_STAGE_CHECK_1" VARCHAR2(10 CHAR), 
    "CC_CLIENT_LIFE_STAGE_BONUS_1" NUMBER(*,0), 
    "CC_CLIENT_LIFE_STAGE_CHECK_2" VARCHAR2(10 CHAR), 
    "CC_CLIENT_LIFE_STAGE_BONUS_2" NUMBER(*,0), 
    "CC_CLIENT_LIFE_STAGE_CHECK_3" VARCHAR2(10 CHAR), 
    "CC_CLIENT_LIFE_STAGE_BONUS_3" NUMBER(*,0), 
    "CC_START_INTENSITY" NUMBER(*,0), 
    "CC_REAL_OFFER_INTENSITY" NUMBER(*,0), 
    "CC_INTENSITY_FALLOFF" NUMBER(*,0), 
    "CC_END_COMMS_OR_TRIGGER" NUMBER(*,0), 
    "CLIENT_STAT_ACT_THRES_UPPR" NUMBER(*,0), 
    "CLIENT_STAT_NEAR_END_THRES_UPPR" NUMBER(*,0), 
    "CLIENT_STAT_EARLY_DOR_THRES_UPPR" NUMBER(*,0), 
    "CLIENT_STAT_DOR_THRES_UPPR" NUMBER(*,0), 
    "CLIENT_STAT_LATE_DOR_THRES_UPPR" NUMBER(*,0), 
    "VALID_TO" TIMESTAMP (6), 
    "CREATED_DTTM" TIMESTAMP (6), 
    "MODIFIED_DTTM" TIMESTAMP (6), 
    "VALID_FROM" TIMESTAMP (6),  
    CONSTRAINT "PK_CALC_PID" PRIMARY KEY ("CALC_PRIORITY_ID") USING INDEX  ENABLE
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
CREATE INDEX IDX_VALIDTO ON LCM_USER.LIFECYCLE_THRESHOLD_DICT (VALID_TO)
/
GRANT SELECT, INSERT, UPDATE, DELETE ON LCM_USER.LIFECYCLE_THRESHOLD_DICT TO MA_TEMP
/
GRANT SELECT ON "LCM_USER"."LIFECYCLE_THRESHOLD_DICT" TO "HCI_RO_LCM_USER"
/