--liquibase formatted.sql
--changeset michael.cawayan:LCM_USER.LIFECYCLE_THRESHOLD_DICT contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
create table LCM_USER.LIFECYCLE_THRESHOLD_DICT
(
CALC_PRIORITY_ID                            INTEGER,
POS_ELIGIBILITY_BASE_REAL                   INTEGER,
POS_ELIGIBILITY_BASE_HOOK                   INTEGER,
POS_ELIGIBILITY_BASE_Engagement             INTEGER,
POS_ELIGIBILITY_BASE_WARMUP                 INTEGER,
POS_OFFER_RESISTANCE_OFFER_COUNT            INTEGER,
POS_SCORE_DROP_OFFER_CYCLE                  INTEGER,
POS_OR_MODIFIER_TRIGGER                     INTEGER,
POS_OR_MODIFIER                             INTEGER,
POS_CLIENT_STATUS_1_CHECK                   VARCHAR2(10 CHAR),
POS_CLIENT_STATUS_1_MODIFIER                INTEGER,
POS_CLIENT_STATUS_2_CHECK                   VARCHAR2(10 CHAR),
POS_CLIENT_STATUS_2_MODIFIER                INTEGER,
POS_CLIENT_STATUS_3_CHECK                   VARCHAR2(10 CHAR),
POS_CLIENT_STATUS_3_MODIFIER                INTEGER,
POS_INTEREST_BONUS                          INTEGER,
POS_DISINTEREST_MINUS                       INTEGER,
POS_CLIENT_LIFE_STAGE_CHECK_1               VARCHAR2(10 CHAR),
POS_CLIENT_LIFE_STAGE_BONUS_1               INTEGER,
POS_CLIENT_LIFE_STAGE_CHECK_2               VARCHAR2(10 CHAR),
POS_CLIENT_LIFE_STAGE_BONUS_2               INTEGER,
POS_CLIENT_LIFE_STAGE_CHECK_3               VARCHAR2(10 CHAR),
POS_CLIENT_LIFE_STAGE_BONUS_3               INTEGER,
POS_START_INTENSITY                         INTEGER,
POS_REAL_OFFER_INTENSITY                    INTEGER,
POS_INTENSITY_FALLOFF                       INTEGER,
POS_END_COMMS_OR_TRIGGER                    INTEGER,
CLX_ELIGIBILITY_BASE_REAL                   INTEGER,
CLX_ELIGIBILITY_BASE_HOOK                   INTEGER,
CLX_ELIGIBILITY_BASE_Engagement             INTEGER,
CLX_ELIGIBILITY_BASE_WARMUP                 INTEGER,
CLX_OFFER_RESISTANCE_OFFER_COUNT            INTEGER,
CLX_SCORE_DROP_OFFER_CYCLE                  INTEGER,
CLX_OR_MODIFIER_TRIGGER                     INTEGER,
CLX_OR_MODIFIER                             INTEGER,
CLX_CLIENT_STATUS_1_CHECK                   VARCHAR2(10 CHAR),
CLX_CLIENT_STATUS_1_MODIFIER                INTEGER,
CLX_CLIENT_STATUS_2_CHECK                   VARCHAR2(10 CHAR),
CLX_CLIENT_STATUS_2_MODIFIER                INTEGER,
CLX_CLIENT_STATUS_3_CHECK                   VARCHAR2(10 CHAR),
CLX_CLIENT_STATUS_3_MODIFIER                INTEGER,
CLX_INTEREST_BONUS                          INTEGER,
CLX_DISINTEREST_MINUS                       INTEGER,
CLX_CLIENT_LIFE_STAGE_CHECK_1               VARCHAR2(10 CHAR),
CLX_CLIENT_LIFE_STAGE_BONUS_1               INTEGER,
CLX_CLIENT_LIFE_STAGE_CHECK_2               VARCHAR2(10 CHAR),
CLX_CLIENT_LIFE_STAGE_BONUS_2               INTEGER,
CLX_CLIENT_LIFE_STAGE_CHECK_3               VARCHAR2(10 CHAR),
CLX_CLIENT_LIFE_STAGE_BONUS_3               INTEGER,
CLX_START_INTENSITY                         INTEGER,
CLX_REAL_OFFER_INTENSITY                    INTEGER,
CLX_INTENSITY_FALLOFF                       INTEGER,
CLX_END_COMMS_OR_TRIGGER                    INTEGER,
CC_ELIGIBILITY_BASE_REAL                    INTEGER,
CC_ELIGIBILITY_BASE_HOOK                    INTEGER,
CC_ELIGIBILITY_BASE_Engagement              INTEGER,
CC_ELIGIBILITY_BASE_WARMUP                  INTEGER,
CC_OFFER_RESISTANCE_OFFER_COUNT             INTEGER,
CC_SCORE_DROP_OFFER_CYCLE                   INTEGER,
CC_OR_MODIFIER_TRIGGER                      INTEGER,
CC_OR_MODIFIER                              INTEGER,
CC_CLIENT_STATUS_1_CHECK                    VARCHAR2(10 CHAR),
CC_CLIENT_STATUS_1_MODIFIER                 INTEGER,
CC_CLIENT_STATUS_2_CHECK                    VARCHAR2(10 CHAR),
CC_CLIENT_STATUS_2_MODIFIER                 INTEGER,
CC_CLIENT_STATUS_3_CHECK                    VARCHAR2(10 CHAR),
CC_CLIENT_STATUS_3_MODIFIER                 INTEGER,
CC_INTEREST_BONUS                           INTEGER,
CC_DISINTEREST_MINUS                        INTEGER,
CC_CLIENT_LIFE_STAGE_CHECK_1                VARCHAR2(10 CHAR),
CC_CLIENT_LIFE_STAGE_BONUS_1                INTEGER,
CC_CLIENT_LIFE_STAGE_CHECK_2                VARCHAR2(10 CHAR),
CC_CLIENT_LIFE_STAGE_BONUS_2                INTEGER,
CC_CLIENT_LIFE_STAGE_CHECK_3                VARCHAR2(10 CHAR),
CC_CLIENT_LIFE_STAGE_BONUS_3                INTEGER,
CC_START_INTENSITY                          INTEGER,
CC_REAL_OFFER_INTENSITY                     INTEGER,
CC_INTENSITY_FALLOFF                        INTEGER,
CC_END_COMMS_OR_TRIGGER                     INTEGER,
CLIENT_STATUS_ACTIVE_THRESHOLD_UPPER        INTEGER,
CLIENT_STATUS_NEAR_END_THRESHOLD_UPPER      INTEGER,
CLIENT_STATUS_EARLY_DORMANT_THRESHOLD_UPPER INTEGER,
CLIENT_STATUS_DORMANT_THRESHOLD_UPPER       INTEGER,
CLIENT_STATUS_LATE_DORMANT_THRESHOLD_UPPER  INTEGER,
VALID_TO                                    TIMESTAMP(6),
CREATED_DTTM                                TIMESTAMP(6),
MODIFIED_DTTM                               TIMESTAMP(6),
CONSTRAINT PK_CALC_PID PRIMARY KEY (CALC_PRIORITY_ID)
  USING INDEX  ENABLE
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON LCM_USER.LIFECYCLE_THRESHOLD_DICT TO MA_TEMP
/