--liquibase formatted.sql
--changeset michael.cawayan:CDM.CIE_LIFECYCLE_OFFER_PRIORITY contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE CDM.CIE_LIFECYCLE_OFFER_PRIORITY 
(
CUID  NUMBER,
CLX_SCORE  NUMBER,
CLX_INTENSITY  NUMBER,
CC_SCORE  NUMBER,
CC_INTENSITY  NUMBER,
POS_SCORE  NUMBER,
POS_INTENSITY  NUMBER,
POS_OFFER_TYPE  VARCHAR2(30 CHAR),
CC_OFFER_TYPE  VARCHAR2(30 CHAR),
CLX_OFFER_TYPE  VARCHAR2(30 CHAR),
CREATED_DATE  TIMESTAMP(6),
STATUS  VARCHAR2(50 CHAR),
SKP_PRIORITY  NUMBER,
ENGAGEMENT_SCORE NUMBER
,ENGAGEMENT_INTENSITY NUMBER
,CLX_WARMUP_SCORE NUMBER
,CLX_WARMUP_INTENSITY NUMBER
,POS_WARMUP_SCORE NUMBER
,POS_WARMUP_INTENSITY NUMBER
,CONSTRAINT PK_CUID PRIMARY KEY (CUID)
  USING INDEX  ENABLE
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO HCI_APP_SELECT
/
GRANT INSERT ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO HCI_APP_INSERT
/
GRANT UPDATE ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO HCI_APP_UPDATE
/
GRANT INSERT ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO APPSUPPORT
/
GRANT SELECT ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO APPSUPPORT
/
GRANT UPDATE ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO APPSUPPORT
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO INTEGRATION
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO MA_TEMP
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO CDM
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO HCPH_CDM_RO
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO HCI_RO_CDM
/
GRANT SELECT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO SAS_CDM_RO
/
GRANT DELETE	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO MA_TEMP
/
GRANT INSERT	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO MA_TEMP
/
GRANT UPDATE	ON CDM.CIE_LIFECYCLE_OFFER_PRIORITY TO MA_TEMP
/
