--liquibase formatted.sql
--changeset michael.cawayan:CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY 
(
    SKP_CLIENT_ELIGIBILITY NUMBER,
    PARTY_ID  NUMBER,
    REAL_CLX_FLAG  NUMBER(1),
    REAL_CC_FLAG  NUMBER(1),
    REAL_POS_FLAG  NUMBER(1),
    ENGAGEMENT_FLAG  NUMBER(1),
    HOOK_CLX_FLAG  NUMBER(1),
    HOOK_CC_FLAG  NUMBER(1),
    HOOK_POS_FLAG  NUMBER(1),
    WARMUP_CLX_FLAG NUMBER(1),
    WARMUP_POS_FLAG NUMBER(1),
    DATE_CREATED  TIMESTAMP(6)
    --CONSTRAINT PK_SKP_ID PRIMARY KEY (SKP_CLIENT_ELIGIBILITY)
  --USING INDEX  ENABLE
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO HCI_APP_SELECT
/
GRANT INSERT ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO HCI_APP_INSERT
/
GRANT UPDATE ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO HCI_APP_UPDATE
/
GRANT INSERT ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO APPSUPPORT
/
GRANT SELECT ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO APPSUPPORT
/
GRANT UPDATE ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO APPSUPPORT
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO INTEGRATION
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO MA_TEMP
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO CDM
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO HCPH_CDM_RO
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO HCI_RO_CDM
/
GRANT SELECT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO SAS_CDM_RO
/
GRANT DELETE	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO MA_TEMP
/
GRANT INSERT	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO MA_TEMP
/
GRANT UPDATE	ON CDM.CLIENT_LIFECYCLE_PRODUCT_ELIGIBILITY TO MA_TEMP
/
